org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#systemProp.http.proxyHost=127.0.0.1
#systemProp.http.proxyPort=10808
#systemProp.https.proxyHost=127.0.0.1
#systemProp.https.proxyPort=10808
#systemProp.http.nonProxyHosts=localhost|127.0.0.1

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.251
# The loader version range can only use the major version of FML as bounds
loader_version_range=[1,)

mod_id=curvyblocks
mod_name=Curvy Blocks
mod_license=AGPL v3
mod_version=1.0.0
mod_group_id=com.lirxowo.curvyblocks
